FROM python:3.10-slim AS base
SHELL ["/bin/bash","-c"]

RUN apt-get update \
 && apt-get install -y --no-install-recommends wget curl git ca-certificates iputils-ping nano procps\
 && rm -rf /var/lib/apt/lists/*

FROM base AS build
SHELL ["/bin/bash","-c"]
RUN wget -q -O - https://www.multichain.com/download/multichain-2.3.3.tar.gz | tar -xzf - -C /tmp
RUN git clone https://github.com/MultiChain/multichain-explorer-2

FROM base AS app
COPY --from=build /tmp/multichain-2.3.3 /usr/local/bin
COPY --from=build /multichain-explorer-2 /root/multichain-explorer-2

WORKDIR /root
CMD ["sleep", "infinity"]