FROM ubuntu:22.04 AS base
SHELL ["/bin/bash","-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential autoconf libtool pkg-config \
    libssl-dev libboost-all-dev \
    wget curl git ca-certificates \
    bsdmainutils \
    && rm -rf /var/lib/apt/lists/*

FROM base AS build
SHELL ["/bin/bash","-c"]

WORKDIR /tmp
RUN git clone https://github.com/MultiChain/multichain.git
RUN cd multichain \
    && git checkout 2.3.x-release \
    && mkdir v8build
RUN wget -q -O - https://github.com/MultiChain/multichain-binaries/raw/master/linux-v8.tar.gz | tar -xzf - -C /tmp/multichain/v8build
RUN cd multichain && ./autogen.sh && ./configure
RUN cd multichain && make
RUN git clone https://github.com/MultiChain/multichain-explorer-2

FROM base AS app
COPY --from=build /tmp/multichain/src/multichaind /usr/local/bin/multichaind
COPY --from=build /tmp/multichain/src/multichain-cli /usr/local/bin/multichain-cli
COPY --from=build /tmp/multichain/src/multichain-util /usr/local/bin/multichain-util
COPY --from=build /tmp/multichain-explorer-2 /root/multichain-explorer-2

WORKDIR /root
CMD ["sleep", "infinity"]