services:
    fin556:
        container_name: fin556
        image: roylai/suss-fin556:0.26.0
        volumes:
            - ..:/workspace:cached
        command: sleep infinity
        network_mode: host
